Support xrpld executable rename

diff --git a/dogfood b/dogfood
--- a/dogfood
+++ b/dogfood
@@ -133,6 +133,16 @@ do
   then
     shift
     wait=1
+  elif [[ "$1" == "--config" ]]
+  then
+    shift
+    configs=( $1 )
+    shift
+  elif [[ "$1" == "--exe" ]]
+  then
+    shift
+    cmake_targets="$1"
+    shift
   elif [[ ${#gdb[@]} > 0 && "$1" == "--" ]]
   then
     shift
@@ -192,6 +202,18 @@ time (
           then
             cmd+=( "--version" )
           fi
+        elif [[ "$target" == "xrpld" ]] && \
+          type -t SimpleXrpldTestLoop >& /dev/null
+        then
+          cmd=( SimpleXrpldTestLoop ${cmake_dirs} )
+          if [[ -n "${configs[@]}" ]]
+          then
+            cmd+=( "${configs[@]}" )
+          fi
+          if [[ ${fast} != 0 ]]
+          then
+            cmd+=( "--version" )
+          fi
         else
           cmd=( SimpleTestLoop "${target}" ${cmake_dirs} )
           if [[ -n "${configs[@]}" ]]
@@ -238,9 +260,9 @@ time (
             then
               if [[ -n "$testdir" ]]
               then
-                rd="${dir}/${testdir}/rippled"
+                rd="${dir}/${testdir}/${target}"
               else
-                rd="${dir}/rippled"
+                rd="${dir}/${target}"
               fi
               cmd=( "${rd}" "--unittest" "--unittest-jobs=$( nproc )" )
               _run "${cmd[@]}" || exit 1
@@ -277,127 +299,130 @@ do
   if [ -e "${cfgfile}" ]
   then
     runpath="${cmake_prefix}${rundir}/${launchdir}"
-    for runfile in rippled{.exe,}
+    for target in ${cmake_targets}
     do
-      if [[ -f "${runpath}/${runfile}" ]]
-      then
-        exe="${runpath}/${runfile}"
-        break
-      fi
-    done
-    if [[ ! -f "${exe}" ]]
-    then
-      echo "Error: Expected executable not found: ${runfile}"
-      break
-    fi
-
-    # Clean up old files
-    for file in "${builddir}/rippled".* "${builddir}/gdb".*
-    do
-      if [[ ! -e "${file}" ]]
-      then
-        continue
-      fi
-
-      echo $file
-      parts=( $( echo "${file}" | sed 's/\./ /g' ) )
-      echo "${parts[@]}"
-      ls -ltr "${builddir}"/*.${parts[1]}*
-      if [[ -e "${builddir}/core.${parts[1]}" ]]
-      then
-        continue
-      fi
-      rm -fv "${builddir}"/*.${parts[1]}*
-    done
-
-    if [[ ${#gdb[@]} > 0 ]] && type -t gdb >& /dev/null
-    then
-      temp=(
-        'set pagination off'
-        "set logging file ${builddir}/gdb.${datestamp}.txt"
-        "run"
-        'tui enable'
-        'winheight src -8'
-        "generate-core-file ${builddir}/core.${datestamp}"
-        # "set logging overwrite on"
-        "set logging enabled on"
-        "thread apply all bt full"
-        # "set logging enabled off"
-        "quit"
-        # "info break"
-        # "delete 2"
-        # "fg"
-        # "thread apply all bt full"
-        # "set logging enabled off"
-      )
-      gdbcommands=()
-      for c in "${temp[@]}"
+      for runfile in ${target}{.exe,}
       do
-        gdbcommands+=( -ex "${c}" )
-      done
-      gdbcommands+=( "--args" )
-    elif [[ ${#gdb[@]} > 0 ]] && type -t lldb >& /dev/null
-    then
-      : "TODO: Figure out how to do fancy startup stuff in lldb"
-      temp=(
-        # 'set pagination off'
-        # "set logging file ${builddir}/gdb.${datestamp}.txt"
-        "run"
-        # 'tui enable'
-        # 'winheight src -8'
-        # "generate-core-file ${builddir}/core.${datestamp}"
-        # "set logging enabled on"
-        # "thread apply all bt full"
-        "quit"
-      )
-      gdbcommands=()
-      for c in "${temp[@]}"
-      do
-        gdbcommands+=( -o "${c}" )
-      done
-      gdbcommands+=( "--" )
-    fi
-
-    # Stop the currently running rippled, if any
-    cmd=( "${exe}" --conf "${cfgfile}" stop )
-    _run "${cmd[@]}" || true
-    # Save the executable
-    cmd=( cp -v "${exe}" "${builddir}/${runfile}.${datestamp}" )
-    _run "${cmd[@]}" || true
-    # Start the new rippled
-    cmd=( "${launch[@]}" "${gdb[@]}" "${gdbcommands[@]}"
-      "${exe}" --conf ${cfgfile} --net "${gdbextra[@]}" )
-    _run --direct "${cmd[@]}" || true
-      : 'https://sourceware.org/gdb/onlinedocs/gdb/TUI-Commands.html'
-      : 'C-x a'
-    if [[ "${#switch}" -gt 0 ]]
-    then
-      _run --direct "${switch[@]}"
-    fi
-
-    # Rotate the logfile(s)
-    if [[ -f $HOME/.logrotate.conf ]] && \
-      grep -q rippled $HOME/.logrotate.conf && \
-      crontab -l | grep -q logrotate
-    then
-      cmd=(
-        eval "$(
-          crontab -l | grep logrotate | \
-          awk '(index($6, "logrotate") != 0) \
-            {l=$6; $1=$2=$3=$4=$5=$6=""; print l " --force --verbose " $0 }'
-        )"
-      )
-      _run "${cmd[@]}" || true
-    else
-      for file in debug.log logs/debug.log log/debug.log \
-          perf.log logs/perf.log log/perf.log
-      do
-        if [ -e "${HOME}/${network}/${file}" ]
+        if [[ -f "${runpath}/${runfile}" ]]
         then
-          mv -vi "${HOME}/${network}/${file}"{,.${datestamp}} || true
+          exe="${runpath}/${runfile}"
+          break
         fi
       done
-    fi
+      if [[ ! -f "${exe}" ]]
+      then
+        echo "Error: Expected executable not found: ${target}"
+        break
+      fi
+
+      # Clean up old files
+      for file in "${builddir}/${target}".* "${builddir}/gdb".*
+      do
+        if [[ ! -e "${file}" ]]
+        then
+          continue
+        fi
+
+        echo $file
+        parts=( $( echo "${file}" | sed 's/\./ /g' ) )
+        echo "${parts[@]}"
+        ls -ltr "${builddir}"/*.${parts[1]}*
+        if [[ -e "${builddir}/core.${parts[1]}" ]]
+        then
+          continue
+        fi
+        rm -fv "${builddir}"/*.${parts[1]}*
+      done
+
+      if [[ ${#gdb[@]} > 0 ]] && type -t gdb >& /dev/null
+      then
+        temp=(
+          'set pagination off'
+          "set logging file ${builddir}/gdb.${datestamp}.txt"
+          "run"
+          'tui enable'
+          'winheight src -8'
+          "generate-core-file ${builddir}/core.${datestamp}"
+          # "set logging overwrite on"
+          "set logging enabled on"
+          "thread apply all bt full"
+          # "set logging enabled off"
+          "quit"
+          # "info break"
+          # "delete 2"
+          # "fg"
+          # "thread apply all bt full"
+          # "set logging enabled off"
+        )
+        gdbcommands=()
+        for c in "${temp[@]}"
+        do
+          gdbcommands+=( -ex "${c}" )
+        done
+        gdbcommands+=( "--args" )
+      elif [[ ${#gdb[@]} > 0 ]] && type -t lldb >& /dev/null
+      then
+        : "TODO: Figure out how to do fancy startup stuff in lldb"
+        temp=(
+          # 'set pagination off'
+          # "set logging file ${builddir}/gdb.${datestamp}.txt"
+          "run"
+          # 'tui enable'
+          # 'winheight src -8'
+          # "generate-core-file ${builddir}/core.${datestamp}"
+          # "set logging enabled on"
+          # "thread apply all bt full"
+          "quit"
+        )
+        gdbcommands=()
+        for c in "${temp[@]}"
+        do
+          gdbcommands+=( -o "${c}" )
+        done
+        gdbcommands+=( "--" )
+      fi
+
+      # Stop the currently running rippled, if any
+      cmd=( "${exe}" --conf "${cfgfile}" stop )
+      _run "${cmd[@]}" || true
+      # Save the executable
+      cmd=( cp -v "${exe}" "${builddir}/${runfile}.${datestamp}" )
+      _run "${cmd[@]}" || true
+      # Start the new rippled
+      cmd=( "${launch[@]}" "${gdb[@]}" "${gdbcommands[@]}"
+        "${exe}" --conf ${cfgfile} --net "${gdbextra[@]}" )
+      _run --direct "${cmd[@]}" || true
+        : 'https://sourceware.org/gdb/onlinedocs/gdb/TUI-Commands.html'
+        : 'C-x a'
+      if [[ "${#switch}" -gt 0 ]]
+      then
+        _run --direct "${switch[@]}"
+      fi
+
+      # Rotate the logfile(s)
+      if [[ -f $HOME/.logrotate.conf ]] && \
+        grep -q rippled $HOME/.logrotate.conf && \
+        crontab -l | grep -q logrotate
+      then
+        cmd=(
+          eval "$(
+            crontab -l | grep logrotate | \
+            awk '(index($6, "logrotate") != 0) \
+              {l=$6; $1=$2=$3=$4=$5=$6=""; print l " --force --verbose " $0 }'
+          )"
+        )
+        _run "${cmd[@]}" || true
+      else
+        for file in debug.log logs/debug.log log/debug.log \
+            perf.log logs/perf.log log/perf.log
+        do
+          if [ -e "${HOME}/${network}/${file}" ]
+          then
+            mv -vi "${HOME}/${network}/${file}"{,.${datestamp}} || true
+          fi
+        done
+      fi
+    done
   else
     echo "Error: config file not found: ${cfgfile}"
   fi
